name = "designium-codingtest"
main = "src/index.js"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DATABASE"
database_name = "designium_db"
database_id = "6994303b-934d-4634-9e7c-df9e6e650937"